#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/basic_data?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
# 配置druid数据源
druid:
  url: jdbc:mysql://localhost:3306/basic_data?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
  driver-class: com.mysql.cj.jdbc.Driver
  username: root
  password: 123456
  initial-size: 1
  min-idle: 1
  max-active: 20
  test-on-borrow: true


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  mapper-locations: classpath*:/mapper/city_division/*.xml
  global-config:
    db-config:
      field-strategy: not_empty
      id-type: auto
      db-type: mysql
    banner: false
#mybatis:
#  configuration:
#    cache-enabled: true

## 配置多环境日志输出格式
  ## 配置包下日志输出格式,可在日志配置文件中直接引用
#logging:
#  level:
#    wd.city_division: debug